name: ciflow

on:
  issue_comment:
    types: [edited]
  pull_request:

jobs:
  ciflow:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: ciflow
        uses: zhouzhuojie/ciflow@bd8a00c2fa56d11a59c604db26aa43eee1e18f31
        with:
          pat-token: ${{secrets.PAT}}
          role: dispatcher
          branch: 'ciflow/**'
          comment-head-fixture: '# ðŸ“š CIFlow Test Plan'
          comment-body-fixture: |
            - [x] #default
              - ciflow_lint.yml
              - ciflow_linux.yml
              - ciflow_windows.yml
              - ciflow_mac.yml
            - [ ] #extra
              - ciflow_linux_extra.yml
              - ciflow_windows_extra.yml
              - ciflow_mac_extra.yml
            - [ ] #cuda
              - ciflow_windows_cuda.yml